/**
 * Book model definition.
 *
 * Represents the shape of a book record stored in Supabase.
 *
 * @typedef {Object} Book
 * @property {string}  id          - UUID generated by Supabase
 * @property {string}  user_id     - UUID of the owner (from auth.users)
 * @property {string}  title       - Book title
 * @property {string}  author      - Author name
 * @property {string}  genre       - Genre / category
 * @property {string}  status      - Reading status: 'Leído' | 'Leyendo' | 'Pendiente'
 * @property {number}  rating      - Rating from 1 to 5
 * @property {string}  notes       - Personal notes
 * @property {string}  created_at  - ISO timestamp
 */

export const READING_STATUSES = ['Leído', 'Leyendo', 'Pendiente'];

export const GENRES = [
  'Ficción',
  'No ficción',
  'Ciencia ficción',
  'Fantasía',
  'Misterio',
  'Romance',
  'Terror',
  'Historia',
  'Biografía',
  'Autoayuda',
  'Tecnología',
  'Otro',
];

/**
 * Creates a default (empty) book object.
 * @returns {Book}
 */
export const createEmptyBook = () => ({
  title: '',
  author: '',
  genre: GENRES[0],
  status: READING_STATUSES[2],
  rating: 1,
  notes: '',
});
